name: Auto Merge development to master

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Dependencies
        run: mvn install

      - name: Run Tests
        run: mvn test

  auto-merge:
    needs: build
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Merge Development into Master
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin master
          git checkout master
          git merge origin/development --no-edit
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
